# Generated by Django 5.0.7 on 2024-08-03 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resturant_name', models.TextField()),
                ('resturant_address', models.TextField()),
                ('resturant_phonenumber', models.IntegerField()),
                ('resturant_email', models.EmailField(max_length=254)),
                ('opening_hour', models.JSONField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roodname', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='images/')),
                ('category', models.CharField(max_length=50)),
                ('vegornot', models.BooleanField()),
                ('available', models.BooleanField(default=True)),
                ('promotion', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_level', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resturant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resturant')),
            ],
        ),
    ]
