# Generated by Django 5.0.7 on 2024-08-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food/images/'),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user/images/'),
        ),
    ]
