# Generated by Django 5.0.7 on 2024-08-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_food_photo_alter_customeuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='isveg',
            field=models.BooleanField(default=False),
        ),
    ]
