# Generated by Django 5.0.7 on 2024-08-03 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_roodname_food_foodname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='resturant_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='food',
            old_name='vegornot',
            new_name='isveg',
        ),
        migrations.DeleteModel(
            name='Resturant',
        ),
    ]
