# Generated by Django 5.0.7 on 2024-08-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_food_isveg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='picture',
        ),
    ]
