# Generated by Django 5.0.7 on 2024-09-29 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_food_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.food')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
