# Generated by Django 5.0.7 on 2024-10-01 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usercart'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderedfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('totalamount', models.IntegerField()),
                ('totalprice', models.IntegerField()),
                ('foodid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.food')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
