# Generated by Django 5.0.7 on 2024-10-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orderedfood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedfood',
            old_name='foodid',
            new_name='orderfoodid',
        ),
        migrations.RenameField(
            model_name='orderedfood',
            old_name='userid',
            new_name='orderuserid',
        ),
    ]
