# Generated by Django 5.0.7 on 2024-10-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_foodid_orderedfood_orderfoodid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orderedfood',
            new_name='orderedfoodbyuser',
        ),
    ]
