# Generated by Django 5.0.7 on 2024-10-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_orderedfood_orderedfoodbyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfoodbyuser',
            name='listedbyhotel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderedfoodbyuser',
            name='pickbydelivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderedfoodbyuser',
            name='pickbyhotel',
            field=models.BooleanField(default=False),
        ),
    ]
