# Generated by Django 5.0.7 on 2024-10-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_orderedfoodbyuser_listedbyhotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfoodbyuser',
            name='rejectbyhotel',
            field=models.BooleanField(default=False),
        ),
    ]
