# Generated by Django 5.0.7 on 2024-10-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderedfoodbyuser_rejectbyhotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfoodbyuser',
            name='addresstodeliver',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
