# Generated by Django 5.0.7 on 2024-10-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_orderedfoodbyuser_addresstodeliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfoodbyuser',
            name='otpfordeliveryman',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='orderedfoodbyuser',
            name='otpforuser',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
