# Generated by Django 5.0.7 on 2024-10-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_orderedfoodbyuser_otpfordeliveryman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfoodbyuser',
            name='deliverymanid',
            field=models.IntegerField(null=True),
        ),
    ]
