# Generated by Django 5.0.7 on 2024-10-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_orderedfoodbyuser_deliverymanid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfoodbyuser',
            name='isdelivered',
            field=models.BooleanField(default=False),
        ),
    ]
